# Generated by Django 4.2.7 on 2024-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=20)),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='photo/')),
                ('adresse', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=100)),
                ('annee_academique', models.CharField(max_length=100)),
                ('nom_pere', models.CharField(max_length=100)),
                ('contact_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('contact_mere', models.CharField(max_length=100)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('contact_tuteur', models.CharField(max_length=100)),
                ('nom_urgence', models.CharField(max_length=100)),
                ('contact_urgence', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
